site_name: Counter-Strike 2 Documentation

nav:
  - Home: index.md
  - Installation: install.md
  - Player Guide: begin.md
  - Skins:
    - Skin Guide: skin.md
    - Markets: markets.md

theme: readthedocs
