site_name: Counter-Strike 2 Documentation

nav:
  - Home: index.md
  - Installation: install.md
  - Player Guide: begin.md
  - Skins:
    - Skin Guide: skin.md
    - Markets: markets.md

theme: 
  name: material
  font: 
    text: Ubuntu

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
